### ISSUE TITLE
require() of ES Module error when generating HTML template

### ISSUE THREAD

**Issue by js-cha** [asyncapi/cli#491]
Versions:
`@asyncapi/cli`: 0.34.0
`@asyncapi/generator`: 1.9.17

Steps to produce:
1. `asyncapi generate fromTemplate ./ws-api.yml  @asyncapi/html-template -o ./asyncapi --force-write`

Errors:
```
require() of ES Module /Users/username/.nvm/versions/node/v16.19.1/lib/node_modules/@asyncapi/generator/node_modules/lodash-es/lodash.js from /Users/username/.nvm/versions/node/v16.19.1/lib/node_modules/@asyncapi/generator/node_modules/@openapi-contrib/openapi-schema-to-json-schema/dist/cjs/lib/converters/schema.js not supported.
Instead change the require of lodash.js in /Users/username/.nvm/versions/node/v16.19.1/lib/node_modules/@asyncapi/generator/node_modules/@openapi-contrib/openapi-schema-to-json-schema/dist/cjs/lib/converters/schema.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by msjof** [comment]
running into same issue

**Comment by jonaslagoni** [comment]
Gonna be fixed by https://github.com/asyncapi/openapi-schema-parser/pull/164

**Comment by derberg** [comment]
hey folks, how are you install CLI? `npm`?

@jonaslagoni look into linked PR please and my last comment

**Comment by js-cha** [comment]
hey @derberg I tried installing CLI via `npm` and also `brew`, regardless of the package manager the errors persist

**Comment by thomaswmanion** [comment]
Workaround to this issue is to install `@openapi-contrib/openapi-schema-to-json-schema@3.2.0`

**Comment by derberg** [comment]
ok, in case of CLI we actually need a fix here https://github.com/asyncapi/parser-js/blob/next-major/package.json#L46

https://github.com/asyncapi/openapi-schema-parser/pull/164 just fixed generator

**Comment by derberg** [comment]
`0.34.1` is out, please let us know if something is not working, we will reopen.

Of course if you use CLI over brew you need to wait longer until they accept and merge automated PR for formula update

**Comment by peter-rr** [comment]
@derberg I'm still having issues while running the tests and installing dependencies: https://github.com/asyncapi/cli/actions/runs/4567602069/jobs/8061591922?pr=418

CLI version used now in master is `0.36.0`. Should I downgrade the version? 🤔

**Comment by msjof** [comment]
this workaround works regardless of cli version:
![image](https://user-images.githubusercontent.com/116612492/228940580-12527b65-4dbb-4c35-9fdf-0249978065a7.png)

**Comment by peter-rr** [comment]
@msjof After applying that workaround in `package-lock.json` I'm getting the error shown below randomly, from a different test in each test execution. Do you think it has something to do with the current issue?

![image](https://user-images.githubusercontent.com/81691177/229111585-7df26637-4bb1-4d89-8570-d62baadc4a1e.png)

**Comment by derberg** [comment]
I'm pretty sure your errors are not related to the issue describe here. Also, https://github.com/openapi-contrib/openapi-schema-to-json-schema also reverted the version that was causing issues. I suggest you ping @Souvikns there in your PR for more help.
